server:
  port: 8763

spring:
  application:
    name: eurka-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: ${spring.application.name}:${server.port}   #修改实例名
    prefer-ip-address: true       #显示IP

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"