spring:
  cloud:
    gateway:
      routes:
        - id: eurka-client
          uri: lb://EURKA-CLIENT
          predicates:
            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'   #获取限流 KEY 的 Bean 的名字
                redis-rate-limiter.replenishRate: 1   #每秒填充速度
                redis-rate-limiter.burstCapacity: 1   #令牌桶总容量
            - StripPrefix=1
  redis:
    host: 49.232.163.247
    port: 6379
    database: 0
    password: redis114


